version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      # - "443:443"   # (Opsional) Buka port 443 nanti kalau sudah pakai HTTPS/SSL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-server
    networks:
      - app-network
    restart: unless-stopped

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: arsiva-backend:latest
    container_name: arsiva-backend
    volumes:
      - /home/artha/arsiva_configs/config.json:/config.json:ro
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin_pn
      POSTGRES_PASSWORD: 2o26jOdmt9eK8CacdPwc
      POSTGRES_DB: production_db
      TZ: Asia/Jakarta
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_pn -d production_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# ==========================================
# Konfigurasi Jaringan & Volume
# ==========================================
networks:
  app-network:
    driver: bridge

volumes:
  pg-data: