events {
    # Jumlah maksimal koneksi simultan yang bisa ditangani Nginx
    worker_connections 1024;
}

http {
    server {
        # Nginx mendengarkan request dari luar di port 80
        listen 80;
        
        # Bisa diganti dengan nama domainmu nanti, misal: api.arsiva.com
        server_name arsiva.id; 

        location /api/ {
            # Mengoper traffic dari Nginx ke container 'api-server' di port 8080
            # Nginx menggunakan jaringan internal Docker untuk memanggil nama service-nya
            proxy_pass http://api-server:3000/;
            
            # Meneruskan IP asli dari user ke backend Go
            # Kalau ini tidak ada, Go kamu akan mengira semua user punya IP internal Nginx
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}