events {
    # Jumlah maksimal koneksi simultan yang bisa ditangani Nginx
    worker_connections 1024;
}

http {
    server {
        # Nginx mendengarkan request dari luar di port 80
        listen 80;
        
        # Bisa diganti dengan nama domainmu nanti, misal: api.arsiva.com
        server_name arsiva.id; 


        location /api/ {
            proxy_pass http://api-server:8080/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / {
            # Mengoper ke container Next.js (Pastikan nama containernya benar)
            proxy_pass http://arsiva_fe:3000;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        


        
    }
}