name: Deploy Go Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Tarik Kode Terbaru
        uses: actions/checkout@v4
        with:
          clean: false # <--- Balik lagi nih, biar gak kena Permission Denied!

      - name: Build Docker Image
        run: |
          docker compose build api-server

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Tarik Kode Terbaru
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Run Unit Tests
        run: |
          # Pakai image golang 1.25 dan install gcc buat handle webp (CGO)
          docker run --rm -v $(pwd):/app -w /app \
            -e CGO_ENABLED=1 \
            golang:1.25-alpine \
            sh -c "apk add --no-cache build-base gcc musl-dev && go test ./..."


  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Tarik Kode Terbaru
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Deploy to Production
        run: |
          # Langsung up tanpa down biar zero downtime
          docker compose up -d --scale api-server=3
          
          echo "Bersihin sampah image..."
          docker image prune -f