name: Deploy Go Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Tarik Kode Terbaru
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "Memulai proses build image..."
          docker compose build api-server

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Tarik Kode Terbaru
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          echo "Menjalankan testing..."
          # Kita jalankan test di dalam container sementara agar environment-nya sama
          docker run --rm -v $(pwd):/app -w /app golang:1.23-alpine go test ./...


  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Tarik Kode Terbaru
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "Semua tes aman, memulai deployment..."
          docker compose up -d
          
          echo "Membersihkan image sampah..."
          docker image prune -f